targets:
  $default:
    builders:
      drift_dev:
        options:
          databases:
            mtds_example: lib/database.dart
          schema_dir: drift_schemas
          test_dir: test/drift
